[supervisord]
nodaemon=true

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:api]
command=python -m app.server
autorestart=true

[program:worker]
command=celery -A app.worker.celery_app worker --concurrency=1
autorestart=true
